# Matter config
CONFIG_CHIP=y
CONFIG_STD_CPP17=y
CONFIG_CHIP_DEVICE_PRODUCT_NAME="NXP DWA app"
CONFIG_CHIP_DEVICE_TYPE=115

#CONFIG_CHIP_WIFI=y

#
# copied from thermostat/nxp/zephyr/prj.conf
#
CONFIG_CHIP_PROJECT_CONFIG="${THERMOSTAT_NXP_ROOT}/main/include/CHIPProjectConfig.h":
CONFIG_CHIP_ENABLE_PAIRING_AUTOSTART=y
CONFIG_CHIP_DEVICE_PRODUCT_ID=32769
CONFIG_CHIP_DEVICE_PRODUCT_NAME="Thermostat"
CONFIG_CHIP_DEVICE_DISCRIMINATOR=0x800

# Bluetooth overrides
CONFIG_BT_DEVICE_NAME="Thermostat"

# Additional configs for debbugging experience.
CONFIG_THREAD_NAME=y
CONFIG_MPU_STACK_GUARD=y

CONFIG_DEBUG=y
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_THREAD_INFO=y
# use this config if stepping during debug session is not consistent
# CONFIG_NO_OPTIMIZATIONS=y
CONFIG_ASSERT=y
# by default west will generate the full assembly output, which can take several minutes when binaries are large
CONFIG_OUTPUT_DISASSEMBLY=n

# enable Matter CLI
CONFIG_CHIP_LIB_SHELL=y

# Build in DWA
CONFIG_BUILD_IN_DWA=y
