CONFIG_EARLY_CONSOLE=y

CONFIG_NETWORKING=y
CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_MAIN_STACK_SIZE=5200
CONFIG_SHELL_STACK_SIZE=5200
CONFIG_NET_TX_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048

CONFIG_NET_PKT_RX_COUNT=10
CONFIG_NET_PKT_TX_COUNT=10
CONFIG_NET_BUF_RX_COUNT=20
CONFIG_NET_BUF_TX_COUNT=20
CONFIG_NET_MAX_CONTEXTS=10
CONFIG_NET_DHCPV4=y

CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n

CONFIG_NET_TCP=y

CONFIG_NET_LOG=y
CONFIG_INIT_STACKS=y

CONFIG_NET_SHELL=y

CONFIG_NET_STATISTICS=y
CONFIG_NET_STATISTICS_PERIODIC_OUTPUT=n

CONFIG_WIFI=y
CONFIG_WIFI_LOG_LEVEL_ERR=y
CONFIG_NET_L2_WIFI_SHELL=y
# printing of scan results puts pressure on queues in new locking
# design in net_mgmt. So, use a higher timeout for a crowded
# environment.
CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=5000
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=16


# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Matter config
CONFIG_CHIP=y
CONFIG_STD_CPP17=y
CONFIG_CHIP_DEVICE_PRODUCT_NAME="NXP DWA app"
CONFIG_CHIP_DEVICE_TYPE=115

#CONFIG_CHIP_WIFI=y

#
# copied from thermostat/nxp/zephyr/prj.conf
#
CONFIG_CHIP_PROJECT_CONFIG="${THERMOSTAT_NXP_ROOT}/main/include/CHIPProjectConfig.h"
CONFIG_CHIP_ENABLE_PAIRING_AUTOSTART=y
CONFIG_CHIP_DEVICE_PRODUCT_ID=32769
CONFIG_CHIP_DEVICE_PRODUCT_NAME="Thermostat"
CONFIG_CHIP_DEVICE_DISCRIMINATOR=0x800

# Bluetooth overrides
CONFIG_BT_DEVICE_NAME="Thermostat"

# Additional configs for debbugging experience.
CONFIG_THREAD_NAME=y
CONFIG_MPU_STACK_GUARD=y

CONFIG_DEBUG=y
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_THREAD_INFO=y
# use this config if stepping during debug session is not consistent
# CONFIG_NO_OPTIMIZATIONS=y
CONFIG_ASSERT=y
# by default west will generate the full assembly output, which can take several minutes when binaries are large
CONFIG_OUTPUT_DISASSEMBLY=n

# enable Matter CLI
CONFIG_CHIP_LIB_SHELL=y

# Build in DWA
CONFIG_BUILD_IN_DWA=y
# -----------------------------------------------------------
